///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeyPostModelUserId = 'userId';
const String _jsonKeyPostModelId = 'id';
const String _jsonKeyPostModelTitle = 'title';
const String _jsonKeyPostModelBody = 'body';

class PostModel {
/*
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
} 
*/

  int? userId;
  int? id;
  String? title;
  String? body;

  PostModel({
    this.userId,
    this.id,
    this.title,
    this.body,
  });
  PostModel.fromJson(dynamic json) {
    userId = json[_jsonKeyPostModelUserId]?.toInt();
    id = json[_jsonKeyPostModelId]?.toInt();
    title = json[_jsonKeyPostModelTitle]?.toString();
    body = json[_jsonKeyPostModelBody]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeyPostModelUserId] = userId;
    data[_jsonKeyPostModelId] = id;
    data[_jsonKeyPostModelTitle] = title;
    data[_jsonKeyPostModelBody] = body;
    return data;
  }
}
